# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 23:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0002_auto_20160630_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=255)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('turno', models.CharField(max_length=15)),
                ('local', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeevento', models.CharField(max_length=255)),
                ('abreviacao', models.CharField(max_length=50)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('textoInicio', models.TextField(default='')),
                ('taxainscricao', models.CharField(max_length=50)),
                ('qtatividades', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InscricaoAtiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluiuativ', models.BooleanField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Atividade')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InscricaoEv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InscriUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etnia', models.CharField(max_length=50)),
                ('estadocivil', models.CharField(default='', max_length=255)),
                ('escolaridade', models.CharField(default='', max_length=255)),
                ('renda', models.CharField(default='', max_length=255)),
                ('profissao', models.CharField(default='', max_length=255)),
                ('academico', models.CharField(default='', max_length=255)),
                ('instituicaodeensino', models.CharField(default='', max_length=255)),
                ('alunotecnico', models.CharField(default='', max_length=255)),
                ('profraps', models.CharField(default='', max_length=255)),
                ('identpublico', models.CharField(default='', max_length=255)),
                ('usuarioservico', models.CharField(default='', max_length=255)),
                ('usuarioservicofamilia', models.CharField(default='', max_length=255)),
                ('japarticipou', models.CharField(default='', max_length=255)),
                ('abordcont', models.CharField(default='', max_length=255)),
                ('partcurso', models.CharField(default='', max_length=255)),
                ('jaauciliou', models.CharField(default='', max_length=255)),
                ('jaaucilioudrogas', models.CharField(default='', max_length=255)),
                ('opiniaodiscussao', models.CharField(default='', max_length=255)),
                ('opiniaoevento', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academico', models.BooleanField()),
                ('curso', models.CharField(max_length=255)),
                ('profsaude', models.BooleanField()),
                ('profissao', models.CharField(max_length=255)),
                ('temposervico', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('raps', models.BooleanField()),
                ('localtrabalho', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('temprapsmental', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('participaant', models.BooleanField()),
                ('saudementalf', models.BooleanField()),
                ('importancia', models.BooleanField()),
                ('justificativa', models.TextField(blank=True, default='', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cep',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='oradorouprofessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
