# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20160826_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriuser',
            name='etnia',
            field=models.CharField(default='', max_length=255),
        ),
    ]
